#!/bin/bash
. ~/.config/hypr/hyprv.conf

restart_waybar() {
    #restart the waybar
    pkill waybar
    waybar & 
}

set_current_background() {
    swww img $SET_BG
}

if [[ "$1" == "vswitch" ]]; then
    restart_waybar
elif [[ "$1" == "setbg" ]]; then
    set_current_background
    restart_waybar
fi
